### ISSUE TITLE
Docker repository leodido/sphinxsearch has been updated

### ISSUE THREAD

**Issue by leodido** [CenturyLinkLabs/docker-sphinx#2]
Hi,

I'm the author of [leodido/sphinxsearch](https://registry.hub.docker.com/u/leodido/sphinxsearch), and I'm writing to you to notify that I have updated the Sphinx Search docker files with latest versions (2.2.8, 2.2.9, and 2.3.1-beta).

Furthermore I have made some improvements to these images:
- directories are now exported as data volumes, like your previous changes had suggested to me
- also custom scripts (searchd.sh and indexall.sh) are now in the PATH
- port order has been flipped for convenient linking
- fix for hungarian source file of libstemmer had already been made also for previous versions of Sphinx Search (<= 2.2.7)

So if you want you can now use this docker image.

I will gladly accept tips, enhancements and especially PR.

**Comment by rupakg** [comment]
@leodido Thank you for making the updates. I will test it and use it in future projects.
